# Количество дней (включая текущую дату), для которых будет запрошен прогноз
FORECAST_DAYS: 3

# Конечная точка для диапазона фильтрации данных по времени.
TIME_FILTER: # "03:00"

# Ваш часовой пояс. Список часовых поясов в нужном формате можно посмотреть здесь - https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TIMEZONE: # "Time/Zone"

# Географическая широта места, для которого запрашиваем прогноз
LATITUDE: # 00.0000

# Географическая долгота места, для которого запрашиваем прогноз
LONGITUDE: # 00.0000

# Максимально приемлемый показатель облачности (%)
CLOUDINESS_FILTER: #20

# API-ключ сервиса погоды meteoblue.com
API_KEY: # "KEY"

# Токен вашего Telegam бота
BOT_TOKEN: # "TOKEN"

# Ваш Chat ID в Telegram
CHAT_ID: # "CHAT ID"